### ISSUE TITLE
Issue while installing backend on CentoS 7

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-backend#476] opened 2019-01-24 15:28 UTC
```
cp lib/Zonemaster/Backend.pm blib/lib/Zonemaster/Backend.pm
cp script/zonemaster_backend_testagent blib/script/zonemaster_backend_testagent
/usr/bin/perl "-Iinc" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/zonemaster_backend_testagent
cp script/zonemaster_backend_rpcapi.psgi blib/script/zonemaster_backend_rpcapi.psgi
/usr/bin/perl "-Iinc" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/zonemaster_backend_rpcapi.psgi
Manifying blib/man1/zonemaster_backend_testagent.1
Manifying blib/man3/Zonemaster::Backend::Config.3pm
Manifying blib/man3/Zonemaster::Backend.3pm
Manifying blib/man3/Zonemaster::Backend::Config::DCPlugin.3pm
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/*.t
Use of uninitialized value in -e at /root/.cpanm/work/1548342651.14421/Zonemaster-Backend-2.1.0/blib/lib/Zonemaster/Backend/TestAgent.pm line 41.
Use of uninitialized value in concatenation (.) or string at /root/.cpanm/work/1548342651.14421/Zonemaster-Backend-2.1.0/blib/lib/Zonemaster/Backend/RPCAPI.pm line 387.
Use of uninitialized value in -e at /root/.cpanm/work/1548342651.14421/Zonemaster-Backend-2.1.0/blib/lib/Zonemaster/Backend/TestAgent.pm line 41.
Attribute (timestamp) does not pass the type constraint because: Validation failed for 'Num' with value 10,8571569919586 at constructor Zonemaster::Engine::Logger::Entry::new (defined at /usr/local/share/perl5/Zonemaster/Engine/Logger/Entry.pm line 144) line 84
        Zonemaster::Engine::Logger::Entry::new('Zonemaster::Engine::Logger::Entry', 'HASH(0x4ec7d38)') called at /usr/local/share/perl5/Zonemaster/Engine/Logger.pm line 24
        Zonemaster::Engine::Logger::add('Zonemaster::Engine::Logger=HASH(0x3d93f30)', 'RECURSE_QUERY', 'HASH(0x4ec7648)') called at /usr/local/share/perl5/Zonemaster/Engine/Recursor.pm line 117
        Zonemaster::Engine::Recursor::_recurse('Zonemaster::Engine::Recursor=HASH(0x1e498f8)', 'Zonemaster::Engine::DNSName=HASH(0x4ec8278)', 'SOA', 'IN', 'HASH(0x578c008)') called at /usr/local/share/perl5/Zonemaster/Engine/Recursor.pm line 61
        Zonemaster::Engine::Recursor::parent('Zonemaster::Engine::Recursor=HASH(0x1e498f8)', 'afnic.fr') called at /usr/local/share/perl5/Zonemaster/Engine.pm line 134
        Zonemaster::Engine::add_fake_delegation('Zonemaster::Engine', 'afnic.fr', 'HASH(0x4eaf350)') called at /root/.cpanm/work/1548342651.14421/Zonemaster-Backend-2.1.0/blib/lib/Zonemaster/Backend/TestAgent.pm line 197
        Zonemaster::Backend::TestAgent::add_fake_delegation('Zonemaster::Backend::TestAgent=HASH(0x507d730)', 'afnic.fr', 'ARRAY(0x583ea38)') called at /root/.cpanm/work/1548342651.14421/Zonemaster-Backend-2.1.0/blib/lib/Zonemaster/Backend/TestAgent.pm line 133
        Zonemaster::Backend::TestAgent::run('Zonemaster::Backend::TestAgent=HASH(0x507d730)', 2) called at t/test01.t line 63
        main::run_zonemaster_test_with_backend_API(2) called at t/test01.t line 83
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 22.
t/test01.t ................
Dubious, test returned 255 (wstat 65280, 0xff00)
All 22 subtests passed
t/test_validate_syntax.t .. ok

Test Summary Report
-------------------
t/test01.t              (Wstat: 65280 Tests: 22 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=2, Tests=49, 14 wallclock secs ( 0.02 usr  0.01 sys +  6.50 cusr  0.18 csys =  6.71 CPU)
Result: FAIL
Failed 1/2 test programs. 0/49 subtests failed.
make: *** [test_dynamic] Error 255
-> FAIL Installing Zonemaster-Backend-2.1.0.tar.gz failed. See /root/.cpanm/work/1548342651.14421/build.log for details. Retry with --force to force install it.
21 distributions installed

```

**Comment by mattias-p** [comment] 2019-01-24 16:25
It's a bug in Perl that was fixed in 5.20. In my opinion it should be worked around in Engine.

See also https://github.com/zonemaster/zonemaster-backend/pull/403#issuecomment-454412963.

**Comment by mattias-p** [comment] 2019-01-24 17:06
Unfortunately I don't have time to try things out, but my general approach is this:

1. Set up an environment where the bug is reproducible in Engine.
2. Create a minimal unit test that fails because of this bug.
3. Come up with a workaround that lets the unit test pass.

Regarding the workaround I have two ideas:

1. Constructing the timestamp value as a string that's being built while locales are temporarily reset using `no locale` and/or setting `LC_ALL` to a friendly value. (like here: https://github.com/zonemaster/zonemaster-engine/blob/master/lib/Zonemaster/Engine/Logger/Entry.pm#L33)
2. Disable the runtime `Num`-validation.

**Comment by sandoche2k** [comment] 2019-01-24 17:08
@vlevigneron i am upgrading to 5.24 to verify whether it will run on CentOS. 

If not, do you think you can do something with respect to the suggestion from @mattias-p

**Comment by sandoche2k** [comment] 2019-01-24 17:21
@mattias-p i have upgraded to 5.24 also and have the same issue

**Comment by sandoche2k** [comment] 2019-01-24 17:23
@vlevigneron if you can make the workaround for centos @pamasse will update zonemaster.fr and zonemaster.net

**Comment by vlevigneron** [comment] 2019-01-24 17:37
@sandoche2k  Well, I'm not at all sure I'll find a way because t/test01.t succeeds on my CentOS environnement.
Can you check if you have properly installed develop branch of all Zonemaster parts (Engine, LDNS, ...) ?

**Comment by vlevigneron** [comment] 2019-01-24 18:06
@sandoche2k I did several tests on several installations and I 'm not able to reproduce this issue... :-(

**Comment by sandoche2k** [comment] 2019-01-24 21:55
@vlevigneron i have reinstalled the centos version 7 and tested the backend again. I have the same error. 
If you want to check, you can connect to the machine via 
ssh zonemaster@vps323914.ovh.net

Password is sent via secure channel

User zonemaster has root access

**Comment by sandoche2k** [comment] 2019-01-25 08:16
the fix enables me to install backend in centos. So can we go for updating zonemaster?

**Closed** 2019-01-25 13:18 UTC
