### ISSUE TITLE
zonemaster-testagent aborting on CentOS 7

### ISSUE THREAD

**Issue by godzone** [zonemaster/zonemaster-backend#505] opened 2019-05-10 22:40 UTC
I am installing on CentOS 7 with postgresql 9.6 (but have tried 9.3 with same result) and cannot get the testagent to run I get the following error but can find no other information to assist in resolving

[agree-24]local: /etc/init.d/zm-backend.sh start
zonemaster-testagent                                          [Started]
DBD::Pg::db selectrow_array failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request. at /usr/local/share/perl5/Zonemaster/Backend/DB.pm line 68.

Any clues as to what to look for would be appreciated. I have tried the latest DBI and DBD::Pg and still get the same result.

I can run the query via psql and it works as expected.

**Comment by sandoche2k** [comment] 2019-05-11 10:06
Can you pull and install from the develop branch. I tested it on CentOS and it was working. There have been changes made to the backend since the last CPAN release.

**Comment by godzone** [comment] 2019-05-12 00:07
> On 11/05/2019, at 10:06 PM, sandoche2k <notifications@github.com> wrote:
> 
> Can you pull and install from the develop branch. I tested it on CentOS and it was working. There have been changes made to the backend since the last CPAN release.
> 
> 

Looks like I need to install Engine from the devel branch as well as Zonemaster/Engine/Profile.pm doesn’t exist.

I appreciate that this probably a dumb question, but how do I do the install from that repo, I downloaded the zip from Backend and then copied the lib stuff to where the original install went but that doesn’t seem to be the correct way to do things to me.

Glen.

**Comment by godzone** [comment] 2019-05-12 00:42
Apologies for my ignorance, I found the install from source instructions in the zonemaster-ldns documentation.  As It seems I need that as well.

**Comment by godzone** [comment] 2019-05-12 02:15
Looking much better now :-)
Getting the following in syslog
 zm-backend.sh: Use of uninitialized value in -e at /usr/local/share/perl5/Zonemaster/Backend/TestAgent.pm line 41.

**Comment by matsduf** [comment] 2019-05-12 20:53
@godzone, we will soon upload the latest release (what you find in the develop branch) to CPAN and then it will be straight forward to install.

**Comment by godzone** [comment] 2019-05-12 23:26
There may still be an issue, after completing the tests the daemon died.

2019-05-12T03:22:57Z [8160] INFO - Test completed: cd1d8e062968706f
2019-05-12T03:22:57Z [8158] INFO - Test completed: 69eafc811d0a0a10
2019-05-12T03:23:01Z [8162] INFO - Test completed: b351f8c595ef95ac
2019-05-12T03:23:08Z [8165] INFO - Test completed: b7c161475b77819d
2019-05-12T03:32:25Z [5069] CRITICAL - DBI connect('database=zonemaster;host=localhost','zonemaster',...) failed: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432? at /usr/local/share/perl5/Zonemaster/Backend/DB/PostgreSQL.pm line 36.
2019-05-12T03:32:25Z [5069] NOTICE - Daemon terminating

Postgresql was still running as simple restarting the zm-backend restarted the daemon.

**Comment by sandoche2k** [comment] 2019-05-13 07:46
@godzone did you follow the install instructions and installed it from CPAN or from the source (i.e. from the develop branch)?

**Comment by godzone** [comment] 2019-05-13 08:12
> On 13/05/2019, at 7:46 PM, sandoche2k <notifications@github.com> wrote:
> 
> @godzone <https://github.com/godzone> did you follow the install instructions and installed it from CPAN or from the source (i.e. from the develop branch)?
> 
> 

Installed from source i.e. develop branch. 

I have re-scanned all our domains 1000+ and the database issue has not re-occured .  Not sure what the issue was but it wasn’t repeatable.

**Comment by sandoche2k** [comment] 2019-05-13 08:59
I also got similar issue while testing. The issue happens intermittently
and it is not reproducible. Related issues:

https://github.com/zonemaster/zonemaster-backend/issues/497
https://github.com/zonemaster/zonemaster-backend/issues/490

**Comment by bitmand** [comment] 2020-04-16 14:59
I experience the same issue on Ubuntu 18.04 with Backend version 4.0.1

I can reproduce this issue by running this multiple times: (as unprivileged user)

    $ /usr/local/bin/zonemaster_backend_testagent start

Some times it starts just fine, but most of the times it throws the error:

    DBD::Pg::db selectrow_array failed: server closed the connection unexpectedly
            This probably means the server terminated abnormally
            before or while processing the request. at /usr/local/share/perl/5.26.1/Zonemaster/Backend/DB.pm line 68.

It looks like the parent process closes the postgresql connection, just before a child process is running a `SELECT id, hash_id FROM... query` which causes a broken pipe and the error message above.

Small part of strace: (the close(5) is the pgsql connection as far as I can tell)
```
[pid 23514] sendto(5, "X\0\0\0\4", 5, MSG_NOSIGNAL, NULL, 0 <unfinished ...>
[pid 23517] close(6 <unfinished ...>
[pid 23514] <... sendto resumed> )      = 5
[pid 23514] close(5)                    = 0
[pid 23514] getpid( <unfinished ...>
[pid 23517] <... close resumed> )       = 0
[pid 23514] <... getpid resumed> )      = 23514
[pid 23514] stat("/tmp/mqq0Ziu5K6", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
[pid 23514] getcwd( <unfinished ...>
[pid 23517] getpid()                    = 23517
[pid 23514] <... getcwd resumed> "/home/zonemaster", 4095) = 17
[pid 23517] sendto(5, "Q\0\0\0c SELECT id, hash_id FROM te"..., 100, MSG_NOSIGNAL, NULL, 0) = -1 EPIPE (Broken pipe)
```

I can provide full strace dumps of both a successful start and when start fails (or more information of any kind) - if anyone is interested?

**Comment by matsduf** [comment] 2020-04-16 15:10
@mtoma, can you take a look at this?

**Comment by bitmand** [comment] 2020-04-17 06:40
@matsduf sure - I can see that a lot of changes have been made to zonemaster_backend_testagent since release 4.0.1, I just couldn't figure out from this issue, if it was fixed or not :)

**Comment by matsduf** [comment] 2020-04-21 11:58
> @matsduf sure - I can see that a lot of changes have been made to zonemaster_backend_testagent since release 4.0.1, I just couldn't figure out from this issue, if it was fixed or not :)

@bitmand, I understand. No problem. We appreciate feedback.

**Comment by mtoma** [comment] 2020-04-21 12:54
Is this still reproductible in testing with the current release?

**Comment by matsduf** [comment] 2020-04-21 14:20
> Is this still reproductible in testing with the current release?

@bitmand says "I experience the same issue on Ubuntu 18.04 with Backend version 4.0.1" which is the current version, or do you mean the upcoming version? Then, nobody has tested.

**Comment by matsduf** [comment] 2020-04-27 18:05
@bitmand, we have investigated further, and we do think that the issue has already been resolved in the develop branch. We will release the content in the develop branch as a new release within days.

**Comment by sandoche2k** [comment] 2020-04-28 16:27
For CentOS 7, I have a VPS running for two days on PSQL 9.3 http://vps803736.ovh.net/domain_check without any issues. Can you try using the develop branch?

**Comment by mattias-p** [comment] 2020-04-29 08:30
Fixed by #529.

**Closed by mattias-p** 2020-04-29 08:30 UTC
Labels: A-TestAgent, T-Bug, T-Question

**Comment by bitmand** [comment] 2020-05-01 09:51
@matsduf thanks for checking - looking forward to testing the new release 👍

**Comment by matsduf** [comment] 2020-05-01 18:32
@bitmand, the new release is here. (Announced on the lists.)

New comments and observations are more than welcome!
