### ISSUE TITLE
make distcheck warning - CentOS7

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-backend#561] opened 2019-11-04 09:14 UTC
make distcheck
/usr/bin/perl "-Iinc" "-MExtUtils::Manifest=fullcheck" -e fullcheck
Not in MANIFEST: script/patch_db_mysql_for_backend_DB_version_lower_than_5.0.0.pl
Not in MANIFEST: script/patch_db_postgresq_for_backend_DB_version_lower_than_5.0.0.pl

**Comment by mattias-p** [comment] 2019-11-04 09:23
Duplicate of #555?

**Closed** 2019-11-04 09:42 UTC
