### ISSUE TITLE
Able to use SQLite for all OS supported

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-backend#250] opened 2016-12-09 08:19 UTC

**Comment by matsduf** [comment] 2019-05-28 14:11
See #177

**Comment by mattias-p** [comment] 2020-09-24 16:06
Is this issue a duplicate of #177 or do they complement each other? It would be nice if a verifiable goal was stated in the issue description.

**Comment by matsduf** [comment] 2021-01-04 21:57
Resolved by #690.

**Closed by matsduf** 2021-01-04 21:57 UTC
